### ISSUE TITLE
IFNG_program3_down means upregulated genes?

### ISSUE THREAD

**Issue by funpys** [longmanz/Mixscale#1]
Hi,

I am little bit confused because of the name of pathway gene list.
For example,  IFNG_program3_down.
What is program3?
And does down means down-regulated genes when IFNG signaling is activated or genes in IFNG singling is KO?

Thanks.

**Comment by longmanz** [comment]
Hi,
The "program" stands for a group of correlated regulators in the IFNG pathway, returned by a MultiCCA-based decomposition method. program3 stands for the third program that was returned by this method. For each program, we provided the list of regulators at https://www.biorxiv.org/content/10.1101/2024.01.29.576933v1.supplementary-material?versioned=true.

As for "down", it means that these genes are down-regulated when the corresponding regulators are **perturbed**, compared to the non-targeting controls. Therefore, these genes should be "**up-regulated**" if the IFNG signaling is activated. In our paper, we mostly focused on the "down" gene lists for each pathway. 

Thank you for bringing this up. I will leave this issue open just in case this might confuse other users as well.

**Comment by funpys** [comment]
@longmanz Thanks a lot!
